import { useMemo } from "react";

import { renderMarkdown } from "@/lib/markdown";

export function Markdown({ source }: { source: string }) {
  const html = useMemo(() => renderMarkdown(source), [source]);

  return (
    <div
      className="markdown-body text-sm leading-relaxed text-foreground"
      // Raw HTML is disabled at the markdown parser level, so this string
      // contains only markup generated by markdown-it itself.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
