/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills.index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as ApiPublicSubmitSkillRouteImport } from './routes/api/public/submit-skill'
import { Route as ApiPublicRefreshGithubCacheRouteImport } from './routes/api/public/refresh-github-cache'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitSkillRoute = ApiPublicSubmitSkillRouteImport.update({
  id: '/api/public/submit-skill',
  path: '/api/public/submit-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshGithubCacheRoute =
  ApiPublicRefreshGithubCacheRouteImport.update({
    id: '/api/public/refresh-github-cache',
    path: '/api/public/refresh-github-cache',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/skills/': typeof SkillsIndexRoute
  '/api/public/refresh-github-cache': typeof ApiPublicRefreshGithubCacheRoute
  '/api/public/submit-skill': typeof ApiPublicSubmitSkillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/skills': typeof SkillsIndexRoute
  '/api/public/refresh-github-cache': typeof ApiPublicRefreshGithubCacheRoute
  '/api/public/submit-skill': typeof ApiPublicSubmitSkillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/skills/': typeof SkillsIndexRoute
  '/api/public/refresh-github-cache': typeof ApiPublicRefreshGithubCacheRoute
  '/api/public/submit-skill': typeof ApiPublicSubmitSkillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/skills/$slug'
    | '/skills/'
    | '/api/public/refresh-github-cache'
    | '/api/public/submit-skill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/skills/$slug'
    | '/skills'
    | '/api/public/refresh-github-cache'
    | '/api/public/submit-skill'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/skills/$slug'
    | '/skills/'
    | '/api/public/refresh-github-cache'
    | '/api/public/submit-skill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  ApiPublicRefreshGithubCacheRoute: typeof ApiPublicRefreshGithubCacheRoute
  ApiPublicSubmitSkillRoute: typeof ApiPublicSubmitSkillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-skill': {
      id: '/api/public/submit-skill'
      path: '/api/public/submit-skill'
      fullPath: '/api/public/submit-skill'
      preLoaderRoute: typeof ApiPublicSubmitSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-github-cache': {
      id: '/api/public/refresh-github-cache'
      path: '/api/public/refresh-github-cache'
      fullPath: '/api/public/refresh-github-cache'
      preLoaderRoute: typeof ApiPublicRefreshGithubCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  ApiPublicRefreshGithubCacheRoute: ApiPublicRefreshGithubCacheRoute,
  ApiPublicSubmitSkillRoute: ApiPublicSubmitSkillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
